name: "Build and test solution"

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: "9.x"

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build and test solution
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Check formatting
        run: |
          dotnet tool restore
          dotnet csharpier check .

      - name: Build
        run: dotnet build --configuration Release --no-restore --no-incremental
